config/routes.rb
Roboterror::Application.routes.draw do
  root to: 'homepages#index'

  resource :admin, only: ['show'] do
    resources :users, only: ['index', 'update'], controller: 'admins_users'
    resources :equipments, controller: 'admins_equipments' do
      resources :stats, only: ['create', 'update', 'destroy'], controller: 'admins_equipments_stats'
    end
  end

  resources :robots do
    resources :inventories, controller: 'robot_inventories'
    resources :fights, only:  ['new', 'create']
    resources :fight_results, only:['show']
  end

  resources :inventories, only: ['new', 'create']
end

app/controllers/admins_equipments_controller.rb
class AdminsEquipmentsController < ApplicationController
  def index
    @equipment = Equipment.all
  end

  def new
    @equipment_types = EquipmentType.all
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(params[:equipment])

    if (@equipment.save)
      redirect_to edit_admin_equipment_path(@equipment)
    else
      render :new
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
    @stats = Stat.all
    @equipment_stats = @equipment.equipment_stats
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.delete
    redirect_to admin_equipments_path
  end
end

app/views/admins_equipments/_equipment_stats.html.erb
<tr data-equipment_stat_id="<%= equipment_stats.id %>">
  <td data-role="stat" data-stat_id="<%= equipment_stats.stat.id %>"><%= equipment_stats.stat.name %></td>
  <td data-role="modifier"><%= equipment_stats.modifier %></td>
  <td data-role="price"><%= equipment_stats.price %></td>
  <td><button data-role="edit">Edit</button> | <button data-role="remove">Remove</button></td>
</tr>

app/views/admins_equipments/edit.html.erb
<%= render 'admins/navigation' %>
<section>
  <h2>Modify Equipment</h2>
  <%= semantic_form_for @equipment, :url => admin_equipment_path(@equipment), :method => :put do |form| %>
    <div class="left half">Price: <span class="money">§<span data-role="equipment_price"><%= @equipment.price %></span></span></div>
    <%= form.inputs do %>
      <%= form.input :name %>
    <% end %>
    <%= form.actions do %>
      <%= form.submit label: 'Save' %>
    <% end %>
  <% end %>
</section>
<section>
<h2>Modify Attributes</h2>
<table data-role="equipment-attributes">
<tr>
  <th>Attribute</th>
  <th>Modifier</th>
  <th>Cost</th>
  <th></th>
</tr>
<%= render collection: @equipment_stats, partial: 'admins_equipments/equipment_stats' %>
<tr data-role="edit_equipment_attributes">
  <td><%= select_tag "stat_id", options_from_collection_for_select(@stats, :id, :name), id: 'edit_equipment_stat_stat' %></td>
  <td><%= number_field_tag 'modifier', 1, :in => -100...100, id: 'edit_equipment_stat_modifier' %></td>
  <td data-for="price"></td>
  <td data-role="buttons"><button data-role="save">Save</button></td>
</tr>
</table>
<%= form_tag admin_equipment_stats_path(@equipment), method: :post,
    remote: true, id: :new_equipment_stat_form do %>
  <%= hidden_field_tag 'equipment_stat[stat_id]', '', id: :new_equipment_stat_stat %>
  <%= hidden_field_tag 'equipment_stat[modifier]', '', id: :new_equipment_stat_modifier %>
  <%= hidden_field_tag 'equipment_stat[equipment_id]', @equipment.id %>
<% end %>
<%= form_tag admin_equipment_stat_path(@equipment, 1), method: :put,
    remote: true, id: :update_equipment_stat_form do %>
  <%= hidden_field_tag 'equipment_stat[stat_id]', '', id: :update_equipment_stat_stat %>
  <%= hidden_field_tag 'equipment_stat[modifier]', '', id: :update_equipment_stat_modifier %>
  <%= hidden_field_tag 'equipment_stat[equipment_id]', @equipment.id %>
  <%= hidden_field_tag 'equipment_stat_id', '', id: :update_equipment_stat_id %>
<% end %>
<%= form_tag admin_equipment_stat_path(@equipment), method: :delete,
    remote: true, id: :delete_equipment_stat_form %>
</section>
<script>
  jQuery(function($) {
    // selectors
    $d = $(document)
    $sel = {}
    $sel['equipment_price'] = "[data-role=equipment_price]"
    $sel['input_row'] = "tr[data-role=edit_equipment_attributes]"
    $sel['input_stat'] = "#edit_equipment_stat_stat"
    $sel['input_modifier'] = "#edit_equipment_stat_modifier"

    $sel['input_buttons_cell'] = $sel['input_row'] + '[data-role=buttons]'

    $sel['new_button'] = "[data-role=save]"

    $sel['new_form'] = "#new_equipment_stat_form"
    $sel['new_stat'] = "#new_equipment_stat_stat"
    $sel['new_modifier'] = "#new_equipment_stat_modifier"

    $sel['edit_button'] = '[data-role=edit]'
    $sel['update_button'] = '[data-role=update]'
    $sel['cancel_button'] = '[data-role=cancel]'

    $sel['update_form'] = "#update_equipment_stat_form"
    $sel['update_stat'] = "#update_equipment_stat_stat"
    $sel['update_equipment_stat_id'] = "#update_equipment_stat_id"
    $sel['update_modifier'] = "#update_equipment_stat_modifier"

    $sel['remove_button'] = '[data-role=remove]'
    $sel['remove_form'] = '#delete_equipment_stat_form'

    $s = select_selectors($sel)

    // html snippets
    $html = {}
    $html['new_button'] = '<button data-role="save">Save</button>'
    $html['edit_button'] = '<button data-role="edit">Edit</button>'
    $html['update_button'] = '<button data-role="update">Update</button>'
    $html['cancel_button'] = '<button data-role="cancel">Cancel</button>'
    $html['remove_button'] = '<button data-role="remove">Remove</button>'

    // events
    $d.on("ajax:success", $sel['new_form'], receive_new_equipment_stat)
    $d.on('click', $sel['new_button'], send_new_equipment_stat)
    $d.on('click', $sel['edit_button'], edit_equipment_stat)
    $d.on('click', $sel['update_button'], send_update_equipment_stat)
    $d.on('ajax:success', $sel['update_form'] , receive_update_equipment_stat)
    $d.on('click', $sel['cancel_button'], cancel_edit_equipment_stat)
    $d.on('click', $sel['remove_button'], send_delete_equipment_stat)
    $d.on('ajax:success', $sel['remove_form'], receive_delete_equipment_stat)

    // new
    function send_new_equipment_stat(){
      $s['new_button'].attr('disabled', 'disabled')
      $s['new_stat'].val($s['input_stat'].val());
      $s['new_modifier'].val($s['input_modifier'].val());
      $s['new_form'].submit()
    }

    function receive_new_equipment_stat(event, data){
      show_new_equipment_stat(data.equipment_stat)
      enable_element($s['new_button'])
      update_equipment_price(data.equipment.price)
    }

    // edit / update
    function edit_equipment_stat(event){
      $clicked = $(event.target)
      $row = $clicked.closest('tr')
      var equipment_stat = get_equipment_stat_from_row($row)
      $s['input_stat'].val(equipment_stat.stat_id)
      $s['input_modifier'].val(equipment_stat.modifier)
      $row.hide()
      $s['input_row'].insertBefore($row)
      $s['update_equipment_stat_id'].val(equipment_stat.id)
      $s['update_form'][0].action = $s['update_form'][0].action.replace(/\d+$/, equipment_stat.id)
      $s['input_buttons_cell'].html($html['update_button'] + ' | ' + $html['cancel_button'])
    }

    function cancel_edit_equipment_stat(event){
      $clicked = $(event.target)
      $row = $clicked.closest('tr')
      $row.next().show()
      reset_input_row()
    }

    function send_update_equipment_stat(){
      disable_element($s['update_button'])
      $s['update_stat'].val($s['input_stat'].val());
      $s['update_modifier'].val($s['input_modifier'].val());
      $s['update_form'].submit()
    }

    function receive_update_equipment_stat(event, data){
      var $row = $s['input_row'].next()
      update_equipment_stat($row, data.euipment_stat)
      update_equipment_price(data.equipment.price)
      $row.show()
      reset_input_row()
    }

    // delete
    function send_delete_equipment_stat(){
      $t = $(this)
      var id = $t.closest('tr').attr('data-equipment_stat_id')
      $s['remove_form'][0].action = $s['remove_form'][0].action.replace(/\d+$/, id)
      disable_element($t)
      $s['remove_form'].submit()
    }

    function receive_delete_equipment_stat(event, data){
      $('tr[data-equipment_stat_id=' + data.equipment_stat.id + ']').remove()
      update_equipment_price(data.equipment.price)
    }

    // render
    function get_equipment_stat_from_row($row){
      return {
        id: $row.attr('data-equipment_stat_id'),
        stat_id: $row.find('[data-role=stat]').attr('data-stat_id'),
        modifier: $row.find('[data-role=modifier]').text()
      }
    }

    function show_new_equipment_stat(equipment_stat){
      $('<tr data-equipment_stat_id="' + equipment_stat.id + '">'+
        '<td data-role="stat" data-stat_id="' + equipment_stat.stat_id + '">' + equipment_stat.stat_name + '</td>'+
        '<td data-role="modifier">' + equipment_stat.modifier + '</td>'+
        '<td data-role="price">' + equipment_stat.price + '</td>'+
        '<td>' + $html['edit_button'] + ' | ' + $html['remove_button'] + '</td>'+
        '</tr>').insertBefore($s['input_row'])
    }

    function update_equipment_stat_row($row, equipment_stat){
      $row.find('td[data-role=stat]').attr('data-stat_id', equipment_stat.stat_id).text(equipment_stat.stat_name)
      $row.find('td[data-role=modifier]').text(equipment_stat.modifier)
      $row.find('td[data-role=price]').text(equipment_stat.price)
    }

    function update_equipment_price(price){
      $s['equipment_price'].text(price)
    }

    function reset_input_row(){
      $s['input_stat'].val(false)
      $s['input_modifier'].val(0)
      $s['input_row'].appendTo($s['input_row'].parent())
      $s['input_buttons_cell'].html($html['new_button'])
    }
  });
</script>

app/views/admins_equipments/index.html.erb
<%= render 'admins/navigation' %>
<section>
<div data-role="equipment_actios">
  <%= link_to "New Equipment", new_admin_equipment_path %>
</div>
</section>
<section>
<table data-role="equipment">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>&nbsp;</th>
  </tr>
  <% @equipment.each do |equipment| %>
    <tr data-equipment="<%= equipment.id %>">
      <td><%= equipment.name %></td>
      <td><%= equipment.price %></td>
      <td><%= link_to "Edit", edit_admin_equipment_path(equipment) %> | <%= link_to "Delete", admin_equipment_path(equipment), method: :delete %></td>
    </tr>
  <% end %>
</table>
</section>

app/views/admins_equipments/new.html.erb
<%= render 'admins/navigation' %>
<section>
<%= semantic_form_for @equipment, :url => admin_equipments_path do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :equipment_type, label: 'Type',  collection: @equipment_types %>
  <% end %>
  <%= form.actions do %>
    <%= form.action :submit, :as => :button, :label => 'Save' %>
  <% end %>
<% end %>
</section>