config/routes.rb
Roboterror::Application.routes.draw do
  root to: 'homepages#index'

  resource :admin, only: ['show'] do
    resources :users, only: ['index', 'update'], controller: 'admins_users'
    resources :equipments, controller: 'admins_equipments' do
      resources :stats, only: ['create', 'update', 'destroy'], controller: 'admins_equipments_stats'
    end
  end

  resources :robots do
    resources :inventories, controller: 'robot_inventories'
    resources :fights, only:  ['new', 'create']
    resources :fight_results, only:['show']
  end

  resources :inventories, only: ['new', 'create']
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    if(current_user)
    else
      @user = User.new
    end
  end
end

app/views/homepages/index.html.erb
<% if current_user %>
  <section class="half left">
    <h2>Pick a fight!</h2>
    <%= render 'robots/opponents' %>
  </section>
  <section class="half right">
    <h2>Combat Log</h2>
    <table>
      <tr>
        <th>Your Robot</th>
        <th>Opponent</th>
        <th>Payout</th>
      </tr>
      <tr>
        <td class="lost">Ralph</td>
        <td class="won">Leroy Jenkins<div class="colorize right">(70%)</div></td>
        <td>§25</td>
      </tr>
      <tr>
        <td class="won">Jimbo<div class="colorize right">(90%)</div></td>
        <td class="lost">Bubba Phat</td>
        <td>§1500</td>
      </tr>
      <tr>
        <td class="won">Ralph<div class="colorize right">(35%)</div></td>
        <td class="lost">Leroy Jenkins</td>
        <td>§250</td>
      </tr>
      <tr>
        <td class="lost">Ralph</td>
        <td class="won">Leroy Jenkins<div class="colorize right">(70%)</div></td>
        <td>§25</td>
      </tr>
    </table>
  <script type="text/javascript">
    $('.colorize').each(function(){
      t = $(this).text()
      m = /\d+/
      if(!m) return
      n = t.match(m)
      g = 128
      h = parseInt((n/100)*g)
      $(this).css({color: 'hsl(' + h +',100% ,33%)'})
    })
  </script>
  </section>
  <section class="half left" data-role="robots">
   <h2>Robot Fleet</h2>
   <%= render 'robots/robots' %>
    <div>
      <%= link_to "Create a Robot", new_robot_path, :class => 'button' %>
    </div>
  </section>
  <section class="half right" data-role="inventory">
    <h2>Iventory</h2>
    <%= render 'inventories/inventories' %>
  <div>
    <%= link_to "Purchase Equipment", new_inventory_path %>
  </div>
  </section>
<% else %>
  <section data-role="welcome-message">
  <p>Welcome the Error Dome. Please sign up or sign in to get started.</p> </section>
  <section class="third left" data-role="sign-up">
    <h3>New users</h3>
    <%= render 'users/form' %>
  </section>
  <section class="third middle">
    <h3>Why Robots are Cool</h3>
    <p>In short this paragraph of text will outlind the key benefits of virtual
       robot combat with your friends. It is quite clear after reading this that
       users should sign up now!</p>
    <ul>
      <li>Key benefit number 1</li>
      <li>Another Key Benefit</li>
      <li>The 'Final' bullet</li>
    </ul>
  </section>
  <section class="third right" data-role="sign-in">
    <h3>Returning users</h3>
    <%= render 'sessions/form' %>
  </section>
<% end %>