config/routes.rb
Roboterror::Application.routes.draw do
  root to: 'homepages#index'

  resource :admin, only: ['show'] do
    resources :users, only: ['index', 'update'], controller: 'admins_users'
    resources :equipments, controller: 'admins_equipments' do
      resources :stats, only: ['create', 'update', 'destroy'], controller: 'admins_equipments_stats'
    end
  end

  resources :robots do
    resources :inventories, controller: 'robot_inventories'
    resources :fights, only:  ['new', 'create']
    resources :fight_results, only:['show']
  end

  resources :inventories, only: ['new', 'create']
end

app/models/robot.rb
class Robot < ActiveRecord::Base
  # Attributes
  attr_accessible :name

  # Associations
  belongs_to :user
  has_many :inventories
  has_many :equipments, through: :inventories

  # Validations
  validates :name, presence: true
  validates :user, presence: true

  def equipped_with?(equipment_type)
    equipments.exists? equipment_type_id: equipment_type.id
  end

  def calculate_price
    equipments.sum(:price)
  end

  def calculate_stats
    stats = {}
    equipments.each do |equipment|
      equipment_stats = equipment.calculate_stats
      stats.merge!(equipment_stats) {|key,src,addend| src + addend}
    end
    stats
  end

  def self.not_owned_by(user)
    where("user_id != #{user.id}")
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def show
    @robot = Robot.find(params[:id])
  end

  def new
    @robot = Robot.new
  end

  def create
    @robot = Robot.new(params[:robot])
    current_user.robots << @robot

    if @robot.save
      redirect_to edit_robot_path(@robot)
    else
      render :new
    end
  end

  def edit
    @robot = Robot.find(params[:id])
    @robot_stats = @robot.calculate_stats
    @stats = Stat.all
    @equipment_types = EquipmentType.all
    @inventories = current_user.inventories
  end

  def update
    @robot = Robot.find(params[:id])
    @robot.update_attributes params[:robot]
    redirect_to root_path
  end

  def destroy
    @robot = Robot.find(params[:id])
    @robot.delete
    redirect_to root_path
  end
end

app/views/robots/_opponents.html.erb
<table data-role="opponents">
  <tr>
    <th>Opponent</th>
    <th>Career Record</th>
    <th colspan="2">Total Value</th>
  </tr>
  <%= render Robot.not_owned_by(current_user) %>
</table>

app/views/robots/_robot.html.erb
<tr data-robot_id="<%= robot.id %>">
  <td data-role="name"><%= robot.name %></td>
  <td><span class="won" data-role="won">0</span>/<span class="lost" data-role="lost">0</span></td>
  <td class="money">§<span data-role="price"><%= robot.calculate_price %></span></td>
  <td>
  <% if current_user.owns(robot) %>
    <%= link_to "edit", edit_robot_path(robot), data: { role: 'edit' }  %>
    <%= link_to "delete", robot_path(robot), method: 'delete', data: { role: 'delete' } %>
 <% else %>
   <%= link_to "view", robot_path(robot), data: { role: 'view' } %>
   <%= link_to "fight", new_robot_fight_path(robot), data: { role: 'fight' } %>
 <% end %>
  </td>
</tr>

app/views/robots/_robots.html.erb
<table data-role="robots">
  <tr>
    <th>Robot Name</th>
    <th>Career Record</th>
    <th colspan="2">Total Value</th>
  </tr>
  <%= render current_user.robots %>
</table>

app/views/robots/edit.html.erb
<section class="left half">
<h2>Configure Your Robot</h2>
<%= semantic_form_for @robot do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
  <% end %>
  <%= form.actions do %>
    <%= form.action :submit, label: "ReDeployz!" %>
  <% end %>
<% end %>
</section>
<section class="right half">
<h3>Current Stats</h3>
<div data-role="robot_stats">
<% @stats.each do |stat| %>
  <div data-stat_id="<%= stat.id %>">
    <span data-role="name"><%= stat.name %></span>
    <span data-role="value"><%= @robot_stats[stat.id] || 0 %></span>
  </div>
<% end %>
</div>
</section>

<section class="left half">
<h3>Equipment Slots</h3>
<div data-role="robot_equipment">
<% @equipment_types.each do |type| %>
  <div data-equipment_type_id="<%= type.id %>">
    <div data-role="name"><%= type.name %></div>
    <div data-role="content">
      <% if @robot.equipped_with?(type)  %>
        <% inventory = @robot.inventories.with_equipment_type(type).first %>
        <div data-role="inventory_item" data-inventory_id="<%= inventory.id %>">
          <%= inventory.equipment.name %>
          <button data-role="unload_equipment">Unload</button>
        </div>
      <% else %>
        <%= select_tag :inventory, options_for_select(@inventories.unassigned.with_equipment_type(type).collect {|inv| [inv.equipment.name , inv.id ] }), prompt: '- Empty -', id: "inventory_for_type_#{type.id}"  %>
        <button data-role="load_equipment" disabled="disabled">Load</button>
      <% end %>
    </div>
  </div>
<% end %>
</div>
</section>

<section class="right half">
<h3>Compatible Inventory</h3>
<div data-role="inventory">
  <% @inventories.unassigned.each do |inventory| %>
      <div data-inventory_id="<%= inventory.id %>" data-equipment_id="<%= inventory.equipment_id %>" data-equipment_type_id="<%= inventory.equipment.equipment_type_id %>">
        <%= %{<span data-role="name">#{inventory.equipment.name}</span> - #{inventory.equipment.price} - #{inventory.equipment.equipment_type.name}}.html_safe %>
      </div>
  <% end %>
</div>
</section>

<%= form_tag robot_inventories_path(@robot), method: :post, remote: true, id: 'attach_form' do %>
  <% hidden_field_tag :inventory_id, '', id: 'attach_inventory' %>
<% end %>

<%= form_tag robot_inventory_path(@robot), method: :delete, remote: true, id: 'detach_form' do %>
  <% hidden_field_tag :inventory_id, '', id: 'detach_inventory' %>
<% end %>

<script language="javascript">
  jQuery(function($) {
    // constants
    EQUIPMENT_TYPES = <%= @equipment_types.to_json.html_safe %>
    STATS = <%= @stats.to_json.html_safe %>

    // selectors
    $d = $(document)
    $sel = {}
    $sel['robot_stats_wrapper'] = '[data-role=robot_stats]'
    $sel['robot_stats'] = $sel['robot_stats_wrapper'] + ' [data-stat_id]'
    $sel['robot_equipment'] = '[data-role=robot_equipment]'
    $sel['attach_selects'] = $sel['robot_equipment'] + ' select'
    $sel['attach_buttons'] = '[data-role=load_equipment]'
    $sel['attach_form'] = '#attach_form'
    $sel['attach_inventory'] = '#attach_inventory'
    $sel['detach_buttons'] = '[data-role=unload_equipment]'
    $sel['detach_form'] = '#detach_form'
    $sel['detach_inventory'] = '#detach_inventory'
    $sel['inventory'] = '[data-role=inventory]'

    $s = select_selectors($sel)

    //test_selectors($s, {verbose: false})
    // events
    $d.on('change', $sel['attach_selects'], toggle_load_button)
    $d.on('click', $sel['attach_buttons'], send_load_equipment)
    $d.on('ajax:success', $sel['attach_form'], receive_load_equipment)
    $d.on('click', $sel['detach_buttons'], send_unload_equipment)
    $d.on('ajax:success', $sel['detach_form'], receive_unload_equipment)

    // html snippets
    $html = {}
    $html['attach_button'] = '<button data-role="load_equipment">Load</button>'
    $html['detach_button'] = '<button data-role="unload_equipment">Unload</button>'

    // attach equipment
    function toggle_load_button(event) {
      $t = $(this)
      if($t.val() == ''){
        $t.next('button').attr('disabled', 'disabled')
      }else{
        $t.next('button').removeAttr('disabled')
      }
    }

    function send_load_equipment(event) {
      $t = $(this)
      inventory_id = $t.parent().find('select').val()
      $s['attach_inventory'].val(inventory_id)
      $s['attach_form'].submit()
    }

    function receive_load_equipment(event, data) {
      show_loaded_inventory(data.inventory, data.equipment)
      show_robot_stats(data.robot_stats)
      remove_inventory(data.inventory)
    }

    // detach equipment
    function send_unload_equipment(event){
      $t = $(this)
      inventory_id = $t.parent().attr('data-inventory_id')
      $s['detach_inventory'].val(inventory_id)
      $s['detach_form'].submit()
    }

    function receive_unload_equipment(event, data) {
      show_robot_stats(data.robot_stats)
      show_inventory_item(data.inventory, data.equipment)
      show_equipment_selector(data.equipment.equipment_type_id)
    }

    // Rendering
    function remove_inventory(inventory){
      $($sel['inventory'] + ' [data-inventory_id="' + inventory.id + '"]').remove()
    }

    function show_loaded_inventory(inventory, equipment){
      $("[data-equipment_type_id='" + equipment.equipment_type_id + "'] [data-role=content]", $s['robot_equipment']).
      html('<div data-role="inventory_item" data-inventory_id="' + inventory.id + '">' +
        equipment.name + ' ' + $html['detach_button'] + '</div>')
    }

    function show_inventory_item(inventory, equipment){
      $s['inventory'].append(
      '<div data-inventory_id="' + inventory.id + '" data-equipment_id="' + equipment +
        '" data-equipment_type_id="' + equipment.equipment_type_id + '">' +
        '<span data-role="name">' + equipment.name + '</span> - ' + equipment.price + ' - ' +
         _.find(EQUIPMENT_TYPES, function(type){return type.id == equipment.equipment_type_id}).name +
      '</div>'
      )
    }

    function show_equipment_selector(equipment_type_id){
      var $select = $('<select name="inventory" id="inventory_for_type_' + equipment_type_id + '">')
      $select.append('<option>- Empty -</option>')
      $($sel['inventory'] + " [data-equipment_type_id='" + equipment_type_id + "']").each(function(index, element){
        $el = $(element)
        var inventory_id = $el.attr('data-inventory_id')
        var equipment_name = $el.find('[data-role=name]').text()
        $select.append('<option value="' + inventory_id + '">' + equipment_name + '</option>')
      })
      $("[data-equipment_type_id='" + equipment_type_id + "'] [data-role=content]", $s['robot_equipment']).html($select).append($html['attach_button'])
    }

    function show_robot_stats(stats){
      console.log(stats)
      $s['robot_stats'].each(function(index, element){
        $el = $(element)
        stat_id = $el.attr('data-stat_id')
        console.log(stats[stat_id])
        $el.find('[data-role=value]').text(stats[stat_id] || 0)
      })
    }

  })
</script>

app/views/robots/new.html.erb
<section>
  <h2>Create a new Robot</h2>
  <%= semantic_form_for @robot do |form| %>
    <%= form.input :name, label: "Robot name" %>
    <%= form.submit "Deployz!!" %>
  <% end %>
</section>