config/routes.rb
Roboterror::Application.routes.draw do
  root to: 'homepages#index'

  resource :admin, only: ['show'] do
    resources :users, only: ['index', 'update'], controller: 'admins_users'
    resources :equipments, controller: 'admins_equipments' do
      resources :stats, only: ['create', 'update', 'destroy'], controller: 'admins_equipments_stats'
    end
  end

  resources :robots do
    resources :inventories, controller: 'robot_inventories'
    resources :fights, only:  ['new', 'create']
    resources :fight_results, only:['show']
  end

  resources :inventories, only: ['new', 'create']
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roboterror</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>" >
    <div class="page-wrapper">
      <% if signed_in? %>
        <div data-role="user-identification">
          <%= current_user.email %>
          <%= link_to "Sign out", "/sign_out", method: :delete %>
          <%= admin_link %>
        </div>
      <% end %>
      <nav data-role="admin-navigation">
        <%= link_to "Users", admin_users_path %>
        <%= link_to "Equipment", admin_equipments_path %>
      </nav>
    <div data-role="flash">
    <% flash.each do |key, value| -%>
      <div class="flash <%= key %>"><%= value %></div>
    <% end -%>
    </div>
    <%= yield %>
    </div>
  </body>
    <%= yield :footer_script %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roboterror</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>" >
    <div class="page-wrapper clearfix">
      <% if signed_in? %>
        <nav class="top right" data-role="user-identification">
          <span class="balance" data-role="balance">&#167;<%= current_user.balance %></span>
          <%= current_user.email %> |
          <%= link_to "Sign out", "/sign_out", method: :delete %>
          <%= admin_link %>
        </nav>
      <% else %>
      <nav class="top right" data-role="user-sign-in">
        <%= link_to "Sign in", "/sign_in" %>
      </nav>
    <% end %>
    <div class="branding">
      <a href="/">
        <h2>RobotError</h2>
        <h3>a game of robotic shenanigans</h3>
      </a>
    </div>
    <div data-role="flash">
    <% flash.each do |key, value| -%>
      <div class="flash <%= key %>"><%= value %></div>
    <% end -%>
    </div>
    <%= yield %>
    </div>
  </body>
    <%= yield :footer_script %>
</html>